name: Run checks before merge Pull Request

on:
  pull_request:
    branches:
      - 'main'

jobs:
  check-subject-dir-mentions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r ci_tools/requirements.txt

    - name: Run check script
      run: python3 -m ci_tools.check_subject_dir_descriptions
